### ISSUE TITLE
how to download model? I'm using cpu.

### ISSUE THREAD

**Issue by datasciritwik** [KoljaB/LocalAIVoiceChat#10]
zephyr-7b-beta.Q5_K_M.gguf

**Comment by KoljaB** [comment]
Click on [zephyr-7b-beta.Q5_K_M.gguf](https://huggingface.co/TheBloke/zephyr-7B-beta-GGUF/blob/main/zephyr-7b-beta.Q5_K_M.gguf), then click on download.

**Comment by datasciritwik** [comment]
cuda not available
llama_cpp_lib: return llama_cpp
Initializing LLM llama.cpp model ...
llama.cpp model initialized
Initializing TTS CoquiEngine ...
 > Using model: xtts


It's stuck from printing the last line. Do we need to pass any model name in the  CoquiEngine(model_name=?) or something ?
