### ISSUE TITLE
error python ai_voicetalk_local.py

### ISSUE THREAD

**Issue by coderwpf** [KoljaB/LocalAIVoiceChat#3]
python ai_voicetalk_local.py

ValueError: Model path does not exist: D:\Projekte\LLaMa\text-gen\text-generation-webui\models\zephyr-7b-beta.Q5_K_M.gguf

**Comment by KoljaB** [comment]
Hey there, 

thanks for your interest in the project.

Please download the model from [here](https://huggingface.co/TheBloke/zephyr-7B-beta-GGUF/blob/main/zephyr-7b-beta.Q5_K_M.gguf), then open the file "creation_params.json" and enter the filepath to the downloaded model under "model_path" ([installation](https://github.com/KoljaB/LocalAIVoiceChat#installation-steps) step 4). 

Hope that helps,
Kolja
