### ISSUE TITLE
license

### ISSUE THREAD

**Issue by UniversalTechno** [KoljaB/LocalAIVoiceChat#5]
if I dont use coqui is it allowed for commercial use ;  thanks

**Comment by KoljaB** [comment]
Can't give legal advice for commercial usage, I'm opensource dev, this is not my terrain. This said both [OpenAI Whisper](https://github.com/openai/whisper/blob/main/LICENSE) model for speech to text as well as the [Zephyr 7B model](https://huggingface.co/HuggingFaceH4/zephyr-7b-beta) are under the MIT license which allows commercial use. 
So if you use another text to speech it should be possible. I wouldn't tho, coqui's new business license for $365 a year is really worth the money imho. Their models have a lot to offer and can do amazing things.
